### PR TITLE
Sync with upstream

### PR DESCRIPTION
**Pull request by nicholasdeepx**
### Description

Sync our `ign-rendering6` branch (including the lidar development) with modifications from upstream.

I ran these:

```
git checkout ign-rendering6
git remote add upstream https://github.com/gazebosim/gz-rendering.git
git fetch upstream
git merge upstream/ign-rendering6
```

Then resolved the conflicts and tried to manually build the library as below, solving any problem along the way.

```
# In the main directory:
docker build -t deepx-gz-rendering .
docker run -dt --name test_gz_rendering deepx-gz-rendering:latest bash
docker exec -it test_gz_rendering bash

# In the container, mimic the commands in CI.
cd /root/gazebo/gz-rendering/build
cmake ..
cmake --build . --target install
ctest
```

For the details of the conflict and build problem resolutions, please see commits from me.

### Motivation and Context

In general, to prepare to upgrade to Gazebo Garden. But this PR is more for the time until the upgrade is finished.
For the time after that, see #12 . 

### How Has This Been Tested?

Through manual build as written earlier, and CI.

### Checklist

- [x] Have you filled the sections above?
- [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same GitHub Issues/ClickUp Task(s)?
- [x] Have you documented the changes in GitHub Issues and/or ClickUp Task(s) related to this Pull Request?
- [x] Have you added labels, where appropriate, to this Pull Request?

### CODE REVIEW

**Comment by wgkassem** [comment]
I'm getting an error while `cmake --build .` in gz-rendering/build
```
[ 11%] Building CXX object src/CMakeFiles/ignition-rendering6.dir/RenderEnginePlugin.cc.o
/root/gz-rendering/src/RenderEngineManager.cc:24:10: fatal error: gz/plugin/Loader.hh: No such file or directory
 #include <gz/plugin/Loader.hh>
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/CMakeFiles/ignition-rendering6.dir/build.make:232: src/CMakeFiles/ignition-rendering6.dir/RenderEngineManager.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:2511: src/CMakeFiles/ignition-rendering6.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 12%] Linking CXX static library ../../../../lib/libterra.a
[ 12%] Built target terra
make: *** [Makefile:163: all] Error 2
root@9ea976c5d8b9:/root/gz-rendering/build#
```

**Comment by wgkassem** [comment]
> I'm getting an error while `cmake --build .` in gz-rendering/build
> 
> ```
> [ 11%] Building CXX object src/CMakeFiles/ignition-rendering6.dir/RenderEnginePlugin.cc.o
> /root/gz-rendering/src/RenderEngineManager.cc:24:10: fatal error: gz/plugin/Loader.hh: No such file or directory
>  #include <gz/plugin/Loader.hh>
>           ^~~~~~~~~~~~~~~~~~~~~
> compilation terminated.
> make[2]: *** [src/CMakeFiles/ignition-rendering6.dir/build.make:232: src/CMakeFiles/ignition-rendering6.dir/RenderEngineManager.cc.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> make[1]: *** [CMakeFiles/Makefile2:2511: src/CMakeFiles/ignition-rendering6.dir/all] Error 2
> make[1]: *** Waiting for unfinished jobs....
> [ 12%] Linking CXX static library ../../../../lib/libterra.a
> [ 12%] Built target terra
> make: *** [Makefile:163: all] Error 2
> root@9ea976c5d8b9:/root/gz-rendering/build#
> ```

I think it's because I am not using the `deepx-gz-rendering` image. I cant pull it 🤔 is it in our hub or is it a custom Dockerfile you wrote?

**Comment by wgkassem** [comment]
It's just looking for https://github.com/gazebosim/gz-plugin/blob/gz-plugin2/loader/include/gz/plugin/Loader.hh basically. We didn't need it before. Can you verify this?

**Comment by nicholasdeepx** [comment]
> I think it's because I am not using the deepx-gz-rendering image. I cant pull it 🤔 is it in our hub or is it a custom Dockerfile you wrote?

I thought `docker build -t deepx-gz-rendering .` in the project directory was supposed to create the deepx-gz-rendering image? Is it not in `docker images`? 🤔

**Comment by nicholasdeepx** [comment]
Speaking of which, which container are you in?

**Comment by wgkassem** [comment]
> Speaking of which, which container are you in?

Oh, I'm building gz-rendering in Talos container

**Comment by wgkassem** [comment]
Oh there she is https://github.com/DeepX-inc/gz-rendering/blob/8573f9f654585de89347cd037d20ec6e946d6ac8/Dockerfile#LL54C13-L54C13

**Comment by nicholasdeepx** [comment]
> Oh there she is https://github.com/DeepX-inc/gz-rendering/blob/8573f9f654585de89347cd037d20ec6e946d6ac8/Dockerfile#LL54C13-L54C13

Ah thank you for noticing 👍 so it has been undetected for ages. I will change this.

**Comment by nicholasdeepx** [comment]
I have removed the offending library. Also wanted to try building in Talos container myself to detect other errors, but may I know how to do it? Do you just clone the branch in Talos container then build it?

**Comment by wgkassem** [comment]
> I have removed the offending library. Also wanted to try building in Talos container myself to detect other errors, but may I know how to do it? Do you just clone the branch in Talos container then build it?

I think we need that library
I just clone the repo, mount it in the Talos container by adjusting the docker-compose.yml, and then follow the build steps using cmake

**Comment by wgkassem** [comment]
> > I'm getting an error while `cmake --build .` in gz-rendering/build
> > ```
> > [ 11%] Building CXX object src/CMakeFiles/ignition-rendering6.dir/RenderEnginePlugin.cc.o
> > /root/gz-rendering/src/RenderEngineManager.cc:24:10: fatal error: gz/plugin/Loader.hh: No such file or directory
> >  #include <gz/plugin/Loader.hh>
> >           ^~~~~~~~~~~~~~~~~~~~~
> > compilation terminated.
> > make[2]: *** [src/CMakeFiles/ignition-rendering6.dir/build.make:232: src/CMakeFiles/ignition-rendering6.dir/RenderEngineManager.cc.o] Error 1
> > make[2]: *** Waiting for unfinished jobs....
> > make[1]: *** [CMakeFiles/Makefile2:2511: src/CMakeFiles/ignition-rendering6.dir/all] Error 2
> > make[1]: *** Waiting for unfinished jobs....
> > [ 12%] Linking CXX static library ../../../../lib/libterra.a
> > [ 12%] Built target terra
> > make: *** [Makefile:163: all] Error 2
> > root@9ea976c5d8b9:/root/gz-rendering/build#
> > ```
> 
> I think it's because I am not using the `deepx-gz-rendering` image. I cant pull it 🤔 is it in our hub or is it a custom Dockerfile you wrote?

Ah so this error is caused by the namespace change
```
root@9ea976c5d8b9:/root/gazebo# ls /usr/include/ignition/plugin1/ignition/plugin/
EnablePluginFromThis.hh  Factory.hh  Loader.hh  PluginPtr.hh  RegisterMore.hh       SpecializedPluginPtr.hh  config.hh  loader
Export.hh                Info.hh     Plugin.hh  Register.hh   SpecializedPlugin.hh  WeakPluginPtr.hh         detail     utility.hh
```
The header is under "ignition/plugin/Loader.hh"

**Comment by wgkassem** [comment]
Ah it's because I'm on 1.3.0
```
root@9ea976c5d8b9:/root/gazebo# dpkg -l | grep ignition-plugin
ii  libignition-plugin:amd64                           1.3.0-1~focal                         amd64        Gazebo Plugin Library - Shared library
ii  libignition-plugin-dev:amd64                       1.3.0-1~focal                         amd64        Gazebo Plugin Library - Development files
root@9ea976c5d8b9:/root/gazebo# apt install libignition-plugin-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  libignition-plugin
The following packages will be upgraded:
  libignition-plugin libignition-plugin-dev
2 upgraded, 0 newly installed, 0 to remove and 563 not upgraded.
Need to get 199 kB of archives.
After this operation, 406 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://packages.osrfoundation.org/gazebo/ubuntu-stable focal/main amd64 libignition-plugin-dev amd64 1.4.0-1~focal [157 kB]
Get:2 http://packages.osrfoundation.org/gazebo/ubuntu-stable focal/main amd64 libignition-plugin amd64 1.4.0-1~focal [42.4 kB]
Fetched 199 kB in 1s (286 kB/s)
debconf: delaying package configuration, since apt-utils is not installed
(Reading database ... 156570 files and directories currently installed.)
Preparing to unpack .../libignition-plugin-dev_1.4.0-1~focal_amd64.deb ...
Unpacking libignition-plugin-dev:amd64 (1.4.0-1~focal) over (1.3.0-1~focal) ...
Preparing to unpack .../libignition-plugin_1.4.0-1~focal_amd64.deb ...
Unpacking libignition-plugin:amd64 (1.4.0-1~focal) over (1.3.0-1~focal) ...
Setting up libignition-plugin:amd64 (1.4.0-1~focal) ...
Setting up libignition-plugin-dev:amd64 (1.4.0-1~focal) ...
Processing triggers for libc-bin (2.31-0ubuntu9.9) ...
```
I need 1.4.0 for the namespace update https://github.com/gazebosim/gz-plugin/tree/ignition-plugin_1.4.0/loader/include
I will try to re-pull the Talos image and rebuild

**Comment by nicholasdeepx** [comment]
As discussed in Daily 2023.05.26, let's drop syncing with 6.
(See [task](https://app.clickup.com/t/864eq9ufj))

**Pull request closed without merging**
